spring:
  thymeleaf:
    prefix: classpath:/templates/ #默认值
    suffix: .html
    mode: LEGACYHTML5 #启用不严格检查html
    encoding: UTF-8
    content-type: text/html
    cache: false #页面热部署

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
# PostgreSQL连接信息
    url: jdbc:postgresql://localhost:5432/thymelte?useUnicode=true&amp;characterEncoding=UTF-8
    username: ENC(hTpbG9fq+7P3SntmXuNtDxbtWDqRuPV+)
    password: ENC(abdq6LyOspryFQHCqzEMTxRozyJVjIA4)
    driver-class-name: org.postgresql.Driver
# MySQL连接信息
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: ENC(hTpbG9fq+7P3SntmXuNtDxbtWDqRuPV+)
#    password: ENC(abdq6LyOspryFQHCqzEMTxRozyJVjIA4)
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization: true

  mail:
    host: smtp.qq.com
    port: 587
    username: simon.sun.dev@qq.com
    password: xjtekyebkhifdjad
    properties:
      mail:
        debug: true
        stmp:
          auth: true
          timeout: 25000
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

security:
  basic:
    enabled: false

jasypt:
  encryptor:
    password: 19941017

server:
  port: 8099
  session:
    timeout: 1800
    persistent: true # 重启时是否持久化session，默认false
  context-path: /thymelte

logging:
  level:
    org.springframework.web: INFO
    hibernate: ERROR

info:
  app:
    name: @project.name@
    description: @project.description@
  build:
    groupId: @project.groupId@
    artifact: @project.artifactId@
    name: @project.name@
    version: @project.version@
  git:
    branch: ${git.branch}
    commit:
      id: ${git.commit.id}
      time: ${git.commit.time}
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

# 获取更全面的git信息
management:
  info:
    git:
      mode: full
  security:
    enabled: false