spring:
  thymeleaf:
    prefix: classpath:/templates/ #默认值
    suffix: .html
    mode: LEGACYHTML5 #启用不严格检查html
    encoding: UTF-8
    content-type: text/html
    cache: false #页面热部署

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
# PostgreSQL连接信息
    url: jdbc:postgresql://localhost:5432/thymelte?useUnicode=true&amp;characterEncoding=UTF-8
    username: ENC(hTpbG9fq+7P3SntmXuNtDxbtWDqRuPV+)
    password: ENC(abdq6LyOspryFQHCqzEMTxRozyJVjIA4)
    driver-class-name: org.postgresql.Driver
# MySQL连接信息
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: ENC(hTpbG9fq+7P3SntmXuNtDxbtWDqRuPV+)
#    password: ENC(abdq6LyOspryFQHCqzEMTxRozyJVjIA4)
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization: true
security:
  basic:
    enabled: false

jasypt:
  encryptor:
    password: 19941017

server:
  port: 8090
  session:
    timeout: 1800
    persistent: true # 重启时是否持久化session，默认false

logging:
  level:
    org.springframework.web: INFO
    hibernate: ERROR